### ISSUE TITLE
[Front end] Add a beautiful grid for sections in Index page

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/Classified-ads-48#24]
Now two sections are put on Bootstrap Navbar, if we add other sections then Navbar would be bloated.

Check [Care.com](https://www.care.com/) for instance, a beautiful grid with icons is so clean and make navigation easier.

**Comment by angelina-tsuboi** [comment]
I would like to work on this!

**Comment by Khushi-Shukla** [comment]
I am willing to work on this issue. Can you you provide more details about the requirement?

**Comment by bacloud14** [comment]
There are no further requirements. 
Unless you installed the package locally and got it running, I will assign this to you.
Thanks !

**Comment by Khushi-Shukla** [comment]
I have installed it locally and and also added .env files in root folder and in client folder. However, I am getting this error whenever I run npm start 
![image](https://user-images.githubusercontent.com/55341533/135742603-49eb8722-843f-47b1-99a1-f2a735cc3965.png)
How can I proceed to solve this error?

**Comment by bacloud14** [comment]
Very nice, as README suggests:
Create MongoDB databases: `listings_db_dev` and `listings_db` with both collections `listing `and `words`

**Comment by Khushi-Shukla** [comment]
Got it. However, MongoDB allows only one free database per user, so how will it work, should I make database from two different ids, or is it necessaary to have them under one profile only?

**Comment by bacloud14** [comment]
You can install locally and have all for free. Anyway you seem to have chosen the cloud. 
Set proper connection URL then in env. 
You can set env as **local or development** and only create **listing_db_dev**

**Comment by bacloud14** [comment]
Don't hesitate to let me know if anything goes wrong.

**Comment by Khushi-Shukla** [comment]
I have created a database and added the url in env. I want to know what values to write in the other fields of both the env files
![image](https://user-images.githubusercontent.com/55341533/135759295-bd475830-3579-446b-8c38-cc15fa8d599c.png)
![image](https://user-images.githubusercontent.com/55341533/135759307-85339d01-816b-4239-b78f-f3dcd607d89c.png)
![image](https://user-images.githubusercontent.com/55341533/135759358-de600b21-0f81-4f36-b954-beb6396c0a4c.png)
Are these values required? If so, what will be the appropriate values

**Comment by bacloud14** [comment]
All keys are very clearly defined in README. Most are not necessary for the app to bootstrap even more not necessary for front-end to show up correctly.

**Comment by bacloud14** [comment]
Your Mongo URL must be unquoted by the way

**Comment by Khushi-Shukla** [comment]
> All keys are very clearly defined in README. Most are not necessary for the app to bootstrap even more not necessary for front-end to show up correctly.

Okay. Will keep you updated.

**Comment by bacloud14** [comment]
try adding /creds/dz-listings-219ed1313c57.json empty file too. 
With 
```
GCLOUD_STORAGE_BUCKET=dz-listings-donations
CREDS_PATH=./creds/dz-listings-219ed1313c57.json
```
Too

**Comment by Khushi-Shukla** [comment]
> Your Mongo URL must be unquoted by the way
Okay. Thank you for the correction

**Comment by Khushi-Shukla** [comment]
I keep getting this error on npm start
![image](https://user-images.githubusercontent.com/55341533/135910313-4453a39f-201d-4aa2-a034-baf549a3bd8b.png)
but the URL is already hardcoded in the app.js for local environment
![image](https://user-images.githubusercontent.com/55341533/135910621-6933379d-88f9-456f-bdcf-9a71835f35c2.png)


Another erro that is shown is this, even though the databse is connected
![image](https://user-images.githubusercontent.com/55341533/135911117-ff1c4d3a-9256-4c2e-9ee9-58b8c0f81b89.png)

The error log is given as:
```
Classified-ads-48> npm start

> classified-ads-48@0.0.0 prestart
> cd client && npm run build:client


> classified-ads-48-client@1.0.0 build:client D:\hacktober\Classified-ads-48\client
> webpack

Environment variables:

[ 'NODE_ENV', 'MONGODB_URI' ]
WebpackBeforeBuildPlugin:
Downloading some data-sets

(node:9984) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (D:\hacktober\Classified-ads-48\node_modules\node-fetch\lib\index.js:1305:9)
    at D:\hacktober\Classified-ads-48\node_modules\node-fetch\lib\index.js:1410:19
    at new Promise (<anonymous>)
    at fetch (D:\hacktober\Classified-ads-48\node_modules\node-fetch\lib\index.js:1407:9)
    at D:\hacktober\Classified-ads-48\client\webpack.config.js:25:23
    at new Promise (<anonymous>)
    at downloadFile (D:\hacktober\Classified-ads-48\client\webpack.config.js:24:10)
    at module.exports.plugins.FileManagerPlugin.events.onStart (D:\hacktober\Classified-ads-48\client\webpack.config.js:79:23)
    at D:\hacktober\Classified-ads-48\client\node_modules\before-build-webpack\index.js:40:9
    at Hook.eval [as callAsync] (eval at create (D:\hacktober\Classified-ads-48\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by 
rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see 
https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:9984) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9984) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (D:\hacktober\Classified-ads-48\node_modules\node-fetch\lib\index.js:1305:9)
    at D:\hacktober\Classified-ads-48\node_modules\node-fetch\lib\index.js:1410:19
    at new Promise (<anonymous>)
    at fetch (D:\hacktober\Classified-ads-48\node_modules\node-fetch\lib\index.js:1407:9)
    at D:\hacktober\Classified-ads-48\client\webpack.config.js:25:23
    at new Promise (<anonymous>)
    at downloadFile (D:\hacktober\Classified-ads-48\client\webpack.config.js:24:10)
    at module.exports.plugins.FileManagerPlugin.events.onStart (D:\hacktober\Classified-ads-48\client\webpack.config.js:80:24)
    at D:\hacktober\Classified-ads-48\client\node_modules\before-build-webpack\index.js:40:9
    at Hook.eval [as callAsync] (eval at create (D:\hacktober\Classified-ads-48\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
(node:9984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by 
rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see 
https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

> classified-ads-48@0.0.0 start
> node bin/www

{ level: 'info', message: 'Checking environment data' }
D:\hacktober\Classified-ads-48\node_modules\@google-cloud\storage\build\src\storage.js:271
            throw new Error('A bucket name is needed to use Cloud Storage.');
            ^

Error: A bucket name is needed to use Cloud Storage.
    at Storage.bucket (D:\hacktober\Classified-ads-48\node_modules\@google-cloud\storage\build\src\storage.js:271:19)
    at Object.<anonymous> (D:\hacktober\Classified-ads-48\lib\routes\listings.js:200:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\hacktober\Classified-ads-48\app.js:235:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

**Comment by bacloud14** [comment]
Excuse my late reply.
Let me please send you some environment keys by email.
Good luck 👍

**Comment by Khushi-Shukla** [comment]
Ok sure.

**Comment by Khushi-Shukla** [comment]
My apologies, your email went to my spam folder so I didn't get notified when you sent the environment keys. I will look into it and will keep you updated.
